@startuml MyExample
skinparam dpi 300

!define DARKBLUE
!include style.puml

together {

class MyClass 
{
  int number
  methodOne()
  methodTwo()
  methodThree()
}

class MyClass2
{
  int number = 0;
}

class CExample
{
public:

  +~CExample() = default;
  +void DoSomething();
  +void DoNothing();
  +void* VeryUsefulMethod(int level);
  +void DoReallyNothing(){}
  +void DoReallyNothingAgain(){}
  +void func1InGroup1(){}
  +void func2InGroup1(){}

  -const char* m_question; ///< the question
  -int m_answer;           ///< the answer 
  -CInnerClass m_innerClass; /// This is an inner class
}

}

together {
object Object01
object Object02
object Object03
object Object04
object Object05
object Object06
object Object07
object Object08

Object01 <|-up- Object02
Object03 *-right- Object04
Object05 o-- "4" Object06
Object07 .. Object08 : some labels
}

@enduml